name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-latest:
    name: Unit Test - iOS 15.4, Xcode 13.3.1
    runs-on: macOS-12
    env: 
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: Scripts/test -d "OS=15.4,name=iPhone 13 Pro"
